# Generated by Django 5.0.6 on 2024-07-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_resourcesnote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteModel',
        ),
    ]
