# Generated by Django 5.0.6 on 2024-07-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_resourceslecture_delete_bookmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LectureModel',
        ),
    ]
