# Generated by Django 5.0.6 on 2024-07-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_resourcesquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
