# Generated by Django 5.0.6 on 2024-07-12 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcesquestion',
            name='question_file',
            field=models.FileField(upload_to='uploads/university/resources/questions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'jpeg'])]),
        ),
    ]
