# Generated by Django 5.0.6 on 2024-07-12 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_alter_resourcesquestion_question_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcesquestion',
            name='question_file',
            field=models.FileField(upload_to='university/resources/questions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'jpeg'])]),
        ),
    ]
