# Generated by Django 5.0.6 on 2024-07-12 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_alter_resourcesquestion_question_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcesbook',
            name='book_file',
            field=models.FileField(upload_to='university/resources/books/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='resourceslecture',
            name='lecture_file',
            field=models.FileField(upload_to='university/resources/lectures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='resourcesnote',
            name='note_file',
            field=models.FileField(upload_to='university/resources/notes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'jpeg'])]),
        ),
    ]
