# Generated by Django 5.0.6 on 2024-07-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_alter_course_semester_alter_course_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesquestion',
            name='uploaded_by_team',
            field=models.CharField(blank=True, choices=[('Maria Islam', 'Maria Islam'), ('Baishakhi Bir', 'Baishakhi Bir'), ('Samia', 'Samia')], max_length=100, null=True),
        ),
    ]
