# Generated by Django 5.0.6 on 2024-07-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_resourcesquestion_uploaded_by_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesbook',
            name='uploaded_by_team',
            field=models.CharField(blank=True, choices=[('Maria Islam', 'Maria Islam'), ('Baishakhi Bir', 'Baishakhi Bir'), ('Ritu Akter Samia', 'Ritu Akter Samia')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resourceslecture',
            name='uploaded_by_team',
            field=models.CharField(blank=True, choices=[('Maria Islam', 'Maria Islam'), ('Baishakhi Bir', 'Baishakhi Bir'), ('Ritu Akter Samia', 'Ritu Akter Samia')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resourcesnote',
            name='uploaded_by_team',
            field=models.CharField(blank=True, choices=[('Maria Islam', 'Maria Islam'), ('Baishakhi Bir', 'Baishakhi Bir'), ('Ritu Akter Samia', 'Ritu Akter Samia')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resourcesquestion',
            name='uploaded_by_team',
            field=models.CharField(blank=True, choices=[('Maria Islam', 'Maria Islam'), ('Baishakhi Bir', 'Baishakhi Bir'), ('Ritu Akter Samia', 'Ritu Akter Samia')], max_length=100, null=True),
        ),
    ]
