# Generated by Django 5.0.6 on 2024-07-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0015_resourcesbook_book_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_edit',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
