# Generated by Django 5.0.6 on 2024-07-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0016_course_last_edit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='last_edit',
            new_name='last_update',
        ),
    ]
