# Generated by Django 5.0.6 on 2024-07-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0017_rename_last_edit_course_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='last_update',
        ),
    ]
