# Generated by Django 5.0.6 on 2024-07-16 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0018_remove_course_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
