# Generated by Django 5.0.6 on 2024-07-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0019_course_faculty_course_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='last_update',
        ),
        migrations.AddField(
            model_name='resourcesbook',
            name='uploaded_by_prev',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resourceslecture',
            name='uploaded_by_prev',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resourcesnote',
            name='uploaded_by_prev',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resourcesquestion',
            name='uploaded_by_prev',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
