# Generated by Django 5.0.6 on 2024-07-18 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0020_remove_course_last_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='faculty',
        ),
    ]
