# Generated by Django 5.0.6 on 2024-07-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0021_remove_course_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesbook',
            name='session',
            field=models.CharField(blank=True, choices=[('24-25', '24-25'), ('23-24', '23-24'), ('22-23', '22-23'), ('21-22', '21-22'), ('20-21', '20-21'), ('19-20', '19-20'), ('18-19', '18-19'), ('17-18', '17-18'), ('16-17', '16-17'), ('15-16', '15-16'), ('14-15', '14-15'), ('13-14', '13-14')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resourceslecture',
            name='session',
            field=models.CharField(blank=True, choices=[('24-25', '24-25'), ('23-24', '23-24'), ('22-23', '22-23'), ('21-22', '21-22'), ('20-21', '20-21'), ('19-20', '19-20'), ('18-19', '18-19'), ('17-18', '17-18'), ('16-17', '16-17'), ('15-16', '15-16'), ('14-15', '14-15'), ('13-14', '13-14')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resourcesnote',
            name='session',
            field=models.CharField(blank=True, choices=[('24-25', '24-25'), ('23-24', '23-24'), ('22-23', '22-23'), ('21-22', '21-22'), ('20-21', '20-21'), ('19-20', '19-20'), ('18-19', '18-19'), ('17-18', '17-18'), ('16-17', '16-17'), ('15-16', '15-16'), ('14-15', '14-15'), ('13-14', '13-14')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resourcesquestion',
            name='session',
            field=models.CharField(blank=True, choices=[('24-25', '24-25'), ('23-24', '23-24'), ('22-23', '22-23'), ('21-22', '21-22'), ('20-21', '20-21'), ('19-20', '19-20'), ('18-19', '18-19'), ('17-18', '17-18'), ('16-17', '16-17'), ('15-16', '15-16'), ('14-15', '14-15'), ('13-14', '13-14')], max_length=50, null=True),
        ),
    ]
