# Generated by Django 5.0.6 on 2024-07-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0024_alter_course_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hour',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
