# Generated by Django 5.0.6 on 2024-07-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0027_alter_resourcesbook_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitytype',
            name='established',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universitytype',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='universitytype',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='university/university_logos/'),
        ),
        migrations.AddField(
            model_name='universitytype',
            name='motto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='universitytype',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcesbook',
            name='uploaded_by_team',
            field=models.CharField(blank=True, choices=[('Maria Islam', 'Maria Islam'), ('Baishakhi Bir', 'Baishakhi Bir'), ('Ritu Akter Samia', 'Ritu Akter Samia'), ('Md. Tanvir Ahmed', 'Md. Tanvir Ahmed'), ('Md Rayhanul Islam Rony', 'Md Rayhanul Islam Rony')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resourceslecture',
            name='uploaded_by_team',
            field=models.CharField(blank=True, choices=[('Maria Islam', 'Maria Islam'), ('Baishakhi Bir', 'Baishakhi Bir'), ('Ritu Akter Samia', 'Ritu Akter Samia'), ('Md. Tanvir Ahmed', 'Md. Tanvir Ahmed'), ('Md Rayhanul Islam Rony', 'Md Rayhanul Islam Rony')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resourcesnote',
            name='uploaded_by_team',
            field=models.CharField(blank=True, choices=[('Maria Islam', 'Maria Islam'), ('Baishakhi Bir', 'Baishakhi Bir'), ('Ritu Akter Samia', 'Ritu Akter Samia'), ('Md. Tanvir Ahmed', 'Md. Tanvir Ahmed'), ('Md Rayhanul Islam Rony', 'Md Rayhanul Islam Rony')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resourcesquestion',
            name='uploaded_by_team',
            field=models.CharField(blank=True, choices=[('Maria Islam', 'Maria Islam'), ('Baishakhi Bir', 'Baishakhi Bir'), ('Ritu Akter Samia', 'Ritu Akter Samia'), ('Md. Tanvir Ahmed', 'Md. Tanvir Ahmed'), ('Md Rayhanul Islam Rony', 'Md Rayhanul Islam Rony')], max_length=100, null=True),
        ),
    ]
