# Generated by Django 5.0.6 on 2024-07-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0028_universitytype_established_universitytype_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitytype',
            name='established',
        ),
        migrations.RemoveField(
            model_name='universitytype',
            name='location',
        ),
        migrations.RemoveField(
            model_name='universitytype',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='universitytype',
            name='motto',
        ),
        migrations.RemoveField(
            model_name='universitytype',
            name='website',
        ),
        migrations.AddField(
            model_name='university',
            name='established',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='university/university_logos/'),
        ),
        migrations.AddField(
            model_name='university',
            name='motto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
