# Generated by Django 5.0.6 on 2024-07-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0029_remove_universitytype_established_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='established',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
