# Generated by Django 5.0.6 on 2024-07-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0032_rename_location_campus_university_location_permanent_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='campus_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
