# Generated by Django 5.0.6 on 2024-08-01 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0036_department_total_semester_or_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcesbook',
            name='year',
        ),
        migrations.RemoveField(
            model_name='resourceslecture',
            name='year',
        ),
        migrations.RemoveField(
            model_name='resourcesnote',
            name='year',
        ),
        migrations.RemoveField(
            model_name='resourcesquestion',
            name='year',
        ),
    ]
