# Generated by Django 5.0.6 on 2024-08-01 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0037_remove_resourcesbook_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
    ]
