# Generated by Django 5.0.6 on 2024-08-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0038_remove_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='academic_staff',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='regular_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='location_permanent_campus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
