# Generated by Django 5.0.6 on 2024-08-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0039_university_academic_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='academic_staff',
            new_name='num_academic_staff',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='regular_students',
            new_name='num_regular_students',
        ),
        migrations.AddField(
            model_name='university',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='num_residence_hall',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
