# Generated by Django 5.0.6 on 2024-08-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0041_alter_resourcesbook_uploaded_by_prev_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='colors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
