# Generated by Django 5.0.6 on 2024-08-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0043_rename_motto_university_motto_bangla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='campus_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
