# Generated by Django 5.0.6 on 2024-08-10 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0044_alter_university_campus_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceslecture',
            name='lecture_file',
            field=models.FileField(upload_to='university/resources/lectures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx', 'odp'])]),
        ),
    ]
