# Generated by Django 5.0.6 on 2024-08-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0045_alter_resourceslecture_lecture_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='course_has_code',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='course_has_credit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='course_has_hour',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('Graduated', 'Graduated')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resourcesbook',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('Graduated', 'Graduated')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resourceslecture',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('Graduated', 'Graduated')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resourcesnote',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('Graduated', 'Graduated')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resourcesquestion',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('Graduated', 'Graduated')], max_length=50, null=True),
        ),
    ]
