# Generated by Django 5.0.6 on 2024-08-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0049_university_type_alter_universitytype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='type',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private'), ('Science and Technology', 'Science and Technology'), ('Engineering', 'Engineering')], default='Public', max_length=100, null=True),
        ),
    ]
