# Generated by Django 5.0.6 on 2024-08-20 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0050_alter_university_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='type',
        ),
    ]
