# Generated by Django 5.0.6 on 2024-08-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0051_remove_university_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='motto_bangla',
            new_name='motto',
        ),
        migrations.RemoveField(
            model_name='university',
            name='motto_english',
        ),
    ]
