# Generated by Django 5.0.6 on 2024-08-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_moderatorrequest_is_running'),
        ('university', '0052_rename_motto_bangla_university_motto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='departments', to='admin_panel.moderatorrequest'),
        ),
    ]
