# Generated by Django 5.0.6 on 2024-08-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0058_department_center_department_institute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='has_center',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='has_department',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='has_discipline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='has_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='has_institute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='has_school',
            field=models.BooleanField(default=False),
        ),
    ]
