# Generated by Django 5.0.6 on 2024-08-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0060_center_layer_department_layer_faculty_layer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='layer',
        ),
        migrations.AddField(
            model_name='university',
            name='layer1',
            field=models.CharField(blank=True, choices=[('university', 'university'), ('faculty', 'faculty'), ('institute', 'institute'), ('school', 'school'), ('center', 'center'), ('department', 'department'), ('discipline', 'discipline'), ('course', 'course'), ('subject', 'subject')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='layer2',
            field=models.CharField(blank=True, choices=[('university', 'university'), ('faculty', 'faculty'), ('institute', 'institute'), ('school', 'school'), ('center', 'center'), ('department', 'department'), ('discipline', 'discipline'), ('course', 'course'), ('subject', 'subject')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='layer3',
            field=models.CharField(blank=True, choices=[('university', 'university'), ('faculty', 'faculty'), ('institute', 'institute'), ('school', 'school'), ('center', 'center'), ('department', 'department'), ('discipline', 'discipline'), ('course', 'course'), ('subject', 'subject')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='layer4',
            field=models.CharField(blank=True, choices=[('university', 'university'), ('faculty', 'faculty'), ('institute', 'institute'), ('school', 'school'), ('center', 'center'), ('department', 'department'), ('discipline', 'discipline'), ('course', 'course'), ('subject', 'subject')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='layer5',
            field=models.CharField(blank=True, choices=[('university', 'university'), ('faculty', 'faculty'), ('institute', 'institute'), ('school', 'school'), ('center', 'center'), ('department', 'department'), ('discipline', 'discipline'), ('course', 'course'), ('subject', 'subject')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='layer6',
            field=models.CharField(blank=True, choices=[('university', 'university'), ('faculty', 'faculty'), ('institute', 'institute'), ('school', 'school'), ('center', 'center'), ('department', 'department'), ('discipline', 'discipline'), ('course', 'course'), ('subject', 'subject')], max_length=100, null=True),
        ),
    ]
