# Generated by Django 5.0.6 on 2024-08-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0061_remove_university_layer_university_layer1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='id_layer1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
