# Generated by Django 5.0.6 on 2024-08-31 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0062_university_id_layer1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='id_layer1',
            new_name='layer1_id',
        ),
    ]
