# Generated by Django 5.0.6 on 2024-08-31 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0063_rename_id_layer1_university_layer1_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('layer', models.PositiveIntegerField(blank=True, null=True)),
                ('established', models.IntegerField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('system', models.CharField(choices=[('Year', 'Year'), ('Semester', 'Semester')], default='semester', max_length=100)),
                ('total_semester_or_year', models.PositiveIntegerField(blank=True, null=True)),
                ('course_has_code', models.BooleanField(default=True)),
                ('course_has_credit', models.BooleanField(default=True)),
                ('course_has_hour', models.BooleanField(default=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.center')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.faculty')),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.institute')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.school')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.university')),
            ],
        ),
    ]
