# Generated by Django 5.0.6 on 2024-09-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0064_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resourcesbook',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resourcesbook',
            name='session',
            field=models.CharField(blank=True, choices=[('25-26', '25-26'), ('24-25', '24-25'), ('23-24', '23-24'), ('22-23', '22-23'), ('21-22', '21-22'), ('20-21', '20-21'), ('19-20', '19-20'), ('18-19', '18-19'), ('17-18', '17-18'), ('16-17', '16-17'), ('15-16', '15-16'), ('14-15', '14-15'), ('13-14', '13-14')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resourceslecture',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resourceslecture',
            name='session',
            field=models.CharField(blank=True, choices=[('25-26', '25-26'), ('24-25', '24-25'), ('23-24', '23-24'), ('22-23', '22-23'), ('21-22', '21-22'), ('20-21', '20-21'), ('19-20', '19-20'), ('18-19', '18-19'), ('17-18', '17-18'), ('16-17', '16-17'), ('15-16', '15-16'), ('14-15', '14-15'), ('13-14', '13-14')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resourcesnote',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resourcesnote',
            name='session',
            field=models.CharField(blank=True, choices=[('25-26', '25-26'), ('24-25', '24-25'), ('23-24', '23-24'), ('22-23', '22-23'), ('21-22', '21-22'), ('20-21', '20-21'), ('19-20', '19-20'), ('18-19', '18-19'), ('17-18', '17-18'), ('16-17', '16-17'), ('15-16', '15-16'), ('14-15', '14-15'), ('13-14', '13-14')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resourcesquestion',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resourcesquestion',
            name='session',
            field=models.CharField(blank=True, choices=[('25-26', '25-26'), ('24-25', '24-25'), ('23-24', '23-24'), ('22-23', '22-23'), ('21-22', '21-22'), ('20-21', '20-21'), ('19-20', '19-20'), ('18-19', '18-19'), ('17-18', '17-18'), ('16-17', '16-17'), ('15-16', '15-16'), ('14-15', '14-15'), ('13-14', '13-14')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='has_center',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='has_department',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='has_discipline',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='has_faculty',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='has_institute',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='has_school',
            field=models.BooleanField(default=True),
        ),
    ]
