# Generated by Django 5.0.6 on 2024-09-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0067_center_created_at_center_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='layer1',
        ),
        migrations.RemoveField(
            model_name='university',
            name='layer1_id',
        ),
        migrations.RemoveField(
            model_name='university',
            name='layer2',
        ),
        migrations.RemoveField(
            model_name='university',
            name='layer3',
        ),
        migrations.RemoveField(
            model_name='university',
            name='layer4',
        ),
        migrations.RemoveField(
            model_name='university',
            name='layer5',
        ),
        migrations.RemoveField(
            model_name='university',
            name='layer6',
        ),
    ]
