# Generated by Django 5.0.6 on 2024-09-08 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0072_rename_layer_institute_total_semester_or_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.faculty'),
        ),
    ]
