# Generated by Django 5.0.6 on 2024-09-10 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_alter_profile_moderator_type'),
        ('university', '0074_commoncourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='first_data_entry_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_data_entry_by', to='account.profile'),
        ),
    ]
