# Generated by Django 5.0.6 on 2024-09-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0075_department_first_data_entry_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commoncourse',
            name='type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Laboratory', 'Laboratory'), ('Sessional', 'Sessional')], default='Theory', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Laboratory', 'Laboratory'), ('Sessional', 'Sessional')], default='Theory', max_length=100),
        ),
    ]
