# Generated by Django 5.0.6 on 2024-09-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0076_course_motivation_course_objectives_course_outcomes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Laboratory', 'Laboratory'), ('Sessional', 'Sessional')], default='Theory', max_length=100),
        ),
    ]
