# Generated by Django 5.0.6 on 2024-09-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0079_alter_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('Theory', 'Theory'), ('Laboratory', 'Laboratory'), ('Sessional', 'Sessional')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(blank=True, choices=[('Mandatory', 'Mandatory'), ('Optional', 'Optional')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(blank=True, choices=[('Theory', 'Theory'), ('Laboratory', 'Laboratory'), ('Sessional', 'Sessional')], max_length=100, null=True),
        ),
    ]
