# Generated by Django 5.0.6 on 2024-09-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0080_alter_course_course_type_alter_course_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commoncourse',
            name='type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Laboratory/Practical', 'Laboratory/Practical'), ('Sessional', 'Sessional'), ('Thesis/Project', 'Thesis/Project')], default='Theory', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('Theory', 'Theory'), ('Laboratory/Practical', 'Laboratory/Practical'), ('Sessional', 'Sessional'), ('Thesis/Project', 'Thesis/Project')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(blank=True, choices=[('Theory', 'Theory'), ('Laboratory/Practical', 'Laboratory/Practical'), ('Sessional', 'Sessional'), ('Thesis/Project', 'Thesis/Project')], max_length=100, null=True),
        ),
    ]
