# Generated by Django 5.0.6 on 2024-09-12 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0081_course_marks_alter_commoncourse_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='syllabus_file',
            field=models.FileField(blank=True, null=True, upload_to='university/syllabus/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'jpeg'])]),
        ),
    ]
