# Generated by Django 5.0.6 on 2024-09-15 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0083_remove_commoncourse_type_commoncourse_course_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesbook',
            name='common_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.commoncourse'),
        ),
        migrations.AddField(
            model_name='resourceslecture',
            name='common_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.commoncourse'),
        ),
        migrations.AddField(
            model_name='resourcesnote',
            name='common_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.commoncourse'),
        ),
        migrations.AddField(
            model_name='resourcesquestion',
            name='common_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.commoncourse'),
        ),
    ]
