# Generated by Django 5.0.6 on 2024-09-15 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0084_resourcesbook_common_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='common_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.commoncourse'),
        ),
    ]
