# Generated by Django 5.0.6 on 2024-09-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0085_course_common_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='common_courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='university.commoncourse'),
        ),
        migrations.AlterField(
            model_name='commoncourse',
            name='course_type',
            field=models.CharField(blank=True, choices=[('Theory', 'Theory'), ('Laboratory/Practical', 'Laboratory/Practical'), ('Sessional', 'Sessional'), ('Thesis/Project', 'Thesis/Project'), ('Viva Voce', 'Viva Voce')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('Theory', 'Theory'), ('Laboratory/Practical', 'Laboratory/Practical'), ('Sessional', 'Sessional'), ('Thesis/Project', 'Thesis/Project'), ('Viva Voce', 'Viva Voce')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(blank=True, choices=[('Theory', 'Theory'), ('Laboratory/Practical', 'Laboratory/Practical'), ('Sessional', 'Sessional'), ('Thesis/Project', 'Thesis/Project'), ('Viva Voce', 'Viva Voce')], max_length=100, null=True),
        ),
    ]
