# Generated by Django 5.0.6 on 2024-09-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0086_course_common_courses_alter_commoncourse_course_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='common_course',
        ),
    ]
