# Generated by Django 5.0.6 on 2024-09-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0087_remove_course_common_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcesbook',
            name='common_course',
        ),
        migrations.RemoveField(
            model_name='resourceslecture',
            name='common_course',
        ),
        migrations.RemoveField(
            model_name='resourcesnote',
            name='common_course',
        ),
        migrations.RemoveField(
            model_name='resourcesquestion',
            name='common_course',
        ),
    ]
