# Generated by Django 5.0.6 on 2024-09-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0088_remove_resourcesbook_common_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesquestion',
            name='common_courses',
            field=models.ManyToManyField(blank=True, to='university.commoncourse'),
        ),
    ]
