# Generated by Django 5.0.6 on 2024-09-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0089_resourcesquestion_common_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesbook',
            name='common_courses',
            field=models.ManyToManyField(blank=True, to='university.commoncourse'),
        ),
        migrations.AddField(
            model_name='resourceslecture',
            name='common_courses',
            field=models.ManyToManyField(blank=True, to='university.commoncourse'),
        ),
        migrations.AddField(
            model_name='resourcesnote',
            name='common_courses',
            field=models.ManyToManyField(blank=True, to='university.commoncourse'),
        ),
    ]
