# Generated by Django 5.0.6 on 2024-09-18 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0058_alter_profile_moderator_type'),
        ('university', '0090_resourcesbook_common_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('Lecturer', 'Lecturer'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.department')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.discipline')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.faculty')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.institute')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.school')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.university')),
            ],
        ),
    ]
