# Generated by Django 5.0.6 on 2024-09-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0092_resourcesquestion_exam_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesquestion',
            name='blank_teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
