# Generated by Django 5.0.6 on 2024-09-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0095_alter_teacher_department_alter_teacher_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
