# Generated by Django 5.0.6 on 2024-08-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='motto',
            new_name='former_name',
        ),
        migrations.AddField(
            model_name='college',
            name='acronym',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='motto_bangla',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='motto_english',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
