# Generated by Django 5.0.6 on 2024-07-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_eduuniversity_department_eduuniversity_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='moderator_type',
            field=models.CharField(blank=True, choices=[('super_moderator', 'super_moderator'), ('university_moderator', 'university_moderator'), ('departmental_moderator', 'departmental_moderator'), ('batch_moderator', 'batch_moderator')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher'), ('Guardian', 'Guardian'), ('Visitor', 'Visitor')], max_length=100, null=True),
        ),
    ]
