# Generated by Django 5.0.6 on 2024-07-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_moderator_type_alter_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='moderator_type',
            field=models.CharField(blank=True, choices=[('super_moderator', 'super_moderator'), ('university_moderator', 'university_moderator'), ('department_moderator', 'department_moderator'), ('batch_moderator', 'batch_moderator')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('3rd', '3rd Semester'), ('4th', '4th Semester'), ('5th', '5th Semester'), ('6th', '6th Semester'), ('7th', '7th Semester'), ('8th', '8th Semester'), ('Graduated', 'Graduated')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='session',
            field=models.CharField(blank=True, choices=[('24-25', '24-25'), ('23-24', '23-24'), ('22-23', '22-23'), ('21-22', '21-22'), ('20-21', '20-21'), ('19-20', '19-20'), ('18-19', '18-19'), ('17-18', '17-18'), ('16-17', '16-17'), ('15-16', '15-16'), ('14-15', '14-15'), ('13-14', '13-14')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.CharField(blank=True, choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year'), ('Graduated', 'Graduated')], max_length=50, null=True),
        ),
    ]
