# Generated by Django 5.0.6 on 2024-07-14 04:13

import apps.account.models.education_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_mobile_number_alter_profile_moderator_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduuniversity',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('3rd', '3rd Semester'), ('4th', '4th Semester'), ('5th', '5th Semester'), ('6th', '6th Semester'), ('7th', '7th Semester'), ('8th', '8th Semester'), ('Graduated', 'Graduated')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eduuniversity',
            name='year',
            field=models.CharField(blank=True, choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year'), ('Graduated', 'Graduated')], default=apps.account.models.education_models.current_year, max_length=50, null=True),
        ),
    ]
