# Generated by Django 5.0.6 on 2024-07-14 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_eduuniversity_departmental_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingusermodel',
            name='requested_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
