# Generated by Django 5.0.6 on 2024-07-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_pendingusermodel_requested_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingusermodel',
            name='requested_user',
        ),
    ]
