# Generated by Django 5.0.6 on 2024-07-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_pendingusermodel_requested_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingusermodel',
            old_name='user',
            new_name='requested_user',
        ),
    ]
