# Generated by Django 5.0.6 on 2024-07-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_user_pendingusermodel_requested_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingusermodel',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
