# Generated by Django 5.0.6 on 2024-07-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_pendingusermodel_requested_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingUserModel',
        ),
    ]
