# Generated by Django 5.0.6 on 2024-07-31 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_delete_pendingusermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
