# Generated by Django 5.0.6 on 2024-08-01 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eduuniversity',
            name='year',
        ),
    ]
