# Generated by Django 5.0.6 on 2024-08-01 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_eduuniversity_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='year',
        ),
    ]
