# Generated by Django 5.0.6 on 2024-08-02 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_profile_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('add_question', 'Add Question'), ('add_book', 'Add Book'), ('add_note', 'Add Note'), ('add_lecture', 'Add Lecture Slide'), ('refer_user', 'Refer User'), ('team_contribution', 'Team Contribution')], max_length=50)),
                ('coins', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to='account.profile')),
            ],
        ),
    ]
