# Generated by Django 5.0.6 on 2024-08-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_eduuniversity_varsity_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='departmental_batch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='session',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='university',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=100, null=True),
        ),
    ]
