# Generated by Django 5.0.6 on 2024-08-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_eduuniversity_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduuniversity',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
