# Generated by Django 5.0.6 on 2024-08-16 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_eduuniversity_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='edu_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_edu_university', to='account.eduuniversity'),
        ),
    ]
