# Generated by Django 5.0.6 on 2024-08-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_profile_edu_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_id_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('public', 'Public')], default='only_me', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('public', 'Public')], default='only_me', max_length=10),
        ),
    ]
