# Generated by Django 5.0.6 on 2024-08-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_eduuniversity_approval_info_eduuniversity_class_roll_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eduuniversity',
            old_name='approval_info',
            new_name='approval_query',
        ),
        migrations.RemoveField(
            model_name='eduuniversity',
            name='class_roll',
        ),
        migrations.AddField(
            model_name='eduuniversity',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
