# Generated by Django 5.0.6 on 2024-08-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_rename_approval_info_eduuniversity_approval_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduuniversity',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
