# Generated by Django 5.0.6 on 2024-08-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_rename_creation_date_eduuniversity_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_id_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('my_batch', 'My Batch'), ('my_department', 'My Department'), ('my_university', 'My University'), ('public', 'Public')], default='only_me', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_scholar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_scholar_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('my_batch', 'My Batch'), ('my_department', 'My Department'), ('my_university', 'My University'), ('public', 'Public')], default='only_me', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_id_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('my_batch', 'My Batch'), ('my_department', 'My Department'), ('my_university', 'My University'), ('public', 'Public')], default='only_me', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_id_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('my_batch', 'My Batch'), ('my_department', 'My Department'), ('my_university', 'My University'), ('public', 'Public')], default='only_me', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_id_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('my_batch', 'My Batch'), ('my_department', 'My Department'), ('my_university', 'My University'), ('public', 'Public')], default='only_me', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_channel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_channel_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('my_batch', 'My Batch'), ('my_department', 'My Department'), ('my_university', 'My University'), ('public', 'Public')], default='only_me', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_id_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('my_batch', 'My Batch'), ('my_department', 'My Department'), ('my_university', 'My University'), ('public', 'Public')], default='only_me', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('my_batch', 'My Batch'), ('my_department', 'My Department'), ('my_university', 'My University'), ('public', 'Public')], default='only_me', max_length=20),
        ),
    ]
