# Generated by Django 5.0.6 on 2024-08-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_profile_blood_group_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('my_batch', 'My Batch'), ('my_department', 'My Department'), ('my_university', 'My University'), ('public', 'Public')], default='only_me', max_length=20),
        ),
    ]
