# Generated by Django 5.0.6 on 2024-08-20 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_profile_moderator_info'),
        ('admin_panel', '0007_moderatorrequest_approved_initial_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='moderator_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_moderator_info', to='admin_panel.moderatorrequest'),
        ),
    ]
