# Generated by Django 5.0.6 on 2024-08-21 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_alter_profile_moderator_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='account.profile'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='activity',
            field=models.CharField(choices=[('add_question', 'Add Question'), ('add_book', 'Add Book'), ('add_note', 'Add Note'), ('add_lecture', 'Add Lecture Slide'), ('refer_new_user', 'Refer New User'), ('team_contribution', 'Team Contribution')], max_length=50),
        ),
    ]
