# Generated by Django 5.0.6 on 2024-08-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_profile_referred_by_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_referral_done',
            field=models.BooleanField(default=False),
        ),
    ]
