# Generated by Django 5.0.6 on 2024-08-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_profile_is_referral_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
