# Generated by Django 5.0.6 on 2024-08-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('my_batch', 'My Batch'), ('my_department', 'My Department'), ('my_university', 'My University'), ('public', 'Public')], default='my_department', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_id_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('my_batch', 'My Batch'), ('my_department', 'My Department'), ('my_university', 'My University'), ('public', 'Public')], default='my_batch', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_id_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('my_batch', 'My Batch'), ('my_department', 'My Department'), ('my_university', 'My University'), ('public', 'Public')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='google_scholar_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('my_batch', 'My Batch'), ('my_department', 'My Department'), ('my_university', 'My University'), ('public', 'Public')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_id_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('my_batch', 'My Batch'), ('my_department', 'My Department'), ('my_university', 'My University'), ('public', 'Public')], default='my_batch', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_id_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('my_batch', 'My Batch'), ('my_department', 'My Department'), ('my_university', 'My University'), ('public', 'Public')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('my_batch', 'My Batch'), ('my_department', 'My Department'), ('my_university', 'My University'), ('public', 'Public')], default='my_batch', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_id_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('my_batch', 'My Batch'), ('my_department', 'My Department'), ('my_university', 'My University'), ('public', 'Public')], default='my_batch', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube_channel_visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('my_batch', 'My Batch'), ('my_department', 'My Department'), ('my_university', 'My University'), ('public', 'Public')], default='public', max_length=20),
        ),
    ]
