# Generated by Django 5.0.6 on 2024-08-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_alter_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_visited_check_referral',
            field=models.BooleanField(default=False),
        ),
    ]
