# Generated by Django 5.0.6 on 2024-08-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_got_previous_cons',
            field=models.BooleanField(default=False),
        ),
    ]
