# Generated by Django 5.0.6 on 2024-08-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_profile_has_got_previous_cons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='has_got_previous_cons',
            new_name='has_clicked_previous_coin_announce',
        ),
    ]
