# Generated by Django 5.0.6 on 2024-08-30 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_rename_has_got_previous_cons_profile_has_clicked_previous_coin_announce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='has_clicked_previous_coin_announce',
            new_name='has_req_for_prev_coin',
        ),
    ]
