# Generated by Django 5.0.6 on 2024-08-31 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_rename_has_clicked_previous_coin_announce_profile_has_req_for_prev_coin'),
        ('university', '0064_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduuniversity',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.center'),
        ),
        migrations.AddField(
            model_name='eduuniversity',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.discipline'),
        ),
        migrations.AddField(
            model_name='eduuniversity',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.institute'),
        ),
        migrations.AddField(
            model_name='eduuniversity',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.school'),
        ),
    ]
