# Generated by Django 5.0.6 on 2024-09-08 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_alter_profile_moderator_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduuniversity',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to='account.profile'),
        ),
    ]
