# Generated by Django 5.0.6 on 2024-09-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_eduuniversity_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='given_prev_coin',
            field=models.BooleanField(default=False),
        ),
    ]
