# Generated by Django 5.0.6 on 2024-09-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blank_task_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(blank=True, choices=[('Added Syllabus in a Department', 'Added Syllabus in a Department')], max_length=200, null=True),
        ),
    ]
