# Generated by Django 5.0.6 on 2024-09-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_task_blank_task_name_alter_task_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(blank=True, choices=[('Added Syllabus/Courses in a Department', 'Added Syllabus/Courses in a Department'), ('Added Info for a University', 'Added Info for a University'), ('Added Previous Resources', 'Added Previous Resources'), ('Video Editing', 'Video Editing'), ('Graphic Design', 'Graphic Design'), ('Script Writing', 'Script Writing'), ('Interview Program', 'Interview Program'), ('Video Timestamp', 'Video Timestamp'), ('Facebook Post', 'Facebook Post')], max_length=200, null=True),
        ),
    ]
