# Generated by Django 5.0.6 on 2024-08-20 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_alter_profile_user_type'),
        ('admin_panel', '0002_pendinguser_remove_adminmodel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_moderator_type', models.CharField(choices=[('super_moderator', 'super_moderator'), ('university_moderator', 'university_moderator'), ('department_moderator', 'department_moderator'), ('batch_moderator', 'batch_moderator')], max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved_initial', models.BooleanField(default=False)),
                ('is_approved_final', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
