# Generated by Django 5.0.6 on 2024-08-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_moderatorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatorrequest',
            name='is_approved_final_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moderatorrequest',
            name='requested_moderator_type',
            field=models.CharField(choices=[('Batch Moderator', 'Batch Moderator'), ('Departmental Moderator', 'Departmental Moderator'), ('University Moderator', 'University Moderator'), ('Central Moderator', 'Central Moderator')], max_length=50),
        ),
    ]
