# Generated by Django 5.0.6 on 2024-08-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_moderatorrequest_is_approved_final_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatorrequest',
            name='is_approved_initial_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
