# Generated by Django 5.0.6 on 2024-08-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_moderatorrequest_is_approved_initial_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderatorrequest',
            old_name='is_approved_final_at',
            new_name='approved_final_at',
        ),
        migrations.RenameField(
            model_name='moderatorrequest',
            old_name='is_approved_initial_at',
            new_name='approved_initial_at',
        ),
    ]
