# Generated by Django 5.0.6 on 2024-08-20 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_alter_profile_moderator_type'),
        ('admin_panel', '0006_rename_is_approved_final_at_moderatorrequest_approved_final_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatorrequest',
            name='approved_initial_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_initial_by', to='account.profile'),
        ),
    ]
