# Generated by Django 5.0.6 on 2024-08-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_moderatorrequest_approved_initial_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatorrequest',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
