# Generated by Django 5.0.6 on 2024-08-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_moderatorrequest_is_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatorrequest',
            name='has_laptop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moderatorrequest',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moderatorrequest',
            name='is_dropped_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moderatorrequest',
            name='write_something',
            field=models.TextField(blank=True, null=True),
        ),
    ]
