# Generated by Django 5.0.6 on 2024-08-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_moderatorrequest_has_laptop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatorrequest',
            name='read_terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
