# Generated by Django 5.0.6 on 2024-09-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_alter_moderatorrequest_requested_moderator_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatorrequest',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
