# Generated by Django 5.0.6 on 2024-09-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_moderatorrequest_is_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorrequest',
            name='requested_moderator_type',
            field=models.CharField(choices=[('Batch Moderator', 'Batch Moderator'), ('Departmental Moderator', 'Departmental Moderator'), ('Discipline Moderator', 'Discipline Moderator'), ('Institute Moderator', 'Institute Moderator'), ('University Moderator', 'University Moderator')], max_length=50),
        ),
    ]
