# Generated by Django 5.0.6 on 2024-09-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_alter_moderatorrequest_requested_moderator_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorrequest',
            name='requested_moderator_type',
            field=models.CharField(choices=[('Batch Moderator', 'Batch Moderator'), ('Departmental Moderator', 'Departmental Moderator'), ('Discipline Moderator', 'Discipline Moderator'), ('Institute Moderator', 'Institute Moderator'), ('University Moderator', 'University Moderator'), ('Central Moderator', 'Central Moderator')], max_length=50),
        ),
    ]
