# Generated by Django 5.0.6 on 2024-08-01 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_alter_askmodel_semester_alter_askmodel_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askmodel',
            name='year',
        ),
    ]
