# Generated by Django 5.0.6 on 2024-10-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='added_job_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Fresher', 'Fresher'), ('Mid-Senior', 'Mid-Senior'), ('Senior', 'Senior'), ('Associate', 'Associate'), ('Executive', 'Executive')], max_length=255, null=True),
        ),
    ]
