# Generated by Django 5.0.6 on 2024-10-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracking', '0003_savedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjobs',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
