# Generated by Django 5.0.6 on 2024-10-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracking', '0004_savedjobs_is_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjobs',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
