# Generated by Django 5.0.6 on 2024-10-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracking', '0007_companylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylist',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
