# Generated by Django 5.0.6 on 2024-10-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracking', '0008_companylist_website_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylist',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
