# Generated by Django 5.0.6 on 2024-10-25 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0058_alter_profile_moderator_type'),
        ('job_tracking', '0010_followee'),
    ]

    operations = [
        migrations.AddField(
            model_name='followee',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
