# Generated by Django 5.0.6 on 2024-07-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('pending_for_verify_users', 'pending_for_verify_users')], max_length=100, null=True),
        ),
    ]
