# Generated by Django 5.0.6 on 2024-08-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_additional_id_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('pending_for_verify_users', 'pending_for_verify_users'), ('approved_as_moderator', 'approved_as_moderator')], max_length=100, null=True),
        ),
    ]
