# Generated by Django 5.0.6 on 2024-08-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='additional_id_two',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
