# Generated by Django 5.0.6 on 2024-09-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_additional_id_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('pending_for_verify_users', 'pending_for_verify_users'), ('approved_as_moderator', 'approved_as_moderator'), ('given_previous_website_coins', 'given_previous_website_coins')], max_length=100, null=True),
        ),
    ]
